### ISSUE TITLE
Wanna make some contribution to a translation

### ISSUE THREAD

**Issue by cyxn** [open-craft-guild/open-source-guide#1]
my email https://privnote.com/bZ6fImh1#8IroriTd3

**Comment by webknjaz** [comment]
Action items:
* [x] invite to @open-source-guild/translators
* [x] invite to slack
  * [x] remove email from public access (to protect from spam-bots)
* [x] assign article/issue for translation

**Comment by webknjaz** [comment]
@cyxn introduce yourself to non-technical people in `#general` channel once you join LambdaBooks Slack.

**Comment by cyxn** [comment]
@webknjaz I'm not really sure that I've been invited to slack. email is right inside of a note

**Comment by webknjaz** [comment]
@denysdovhan help

**Comment by denysdovhan** [comment]
Done

**Comment by webknjaz** [comment]
@cyxn pick an issue, create a branch (name it `translation/##-article-name`) and start working on it.
