### ISSUE TITLE
Help with translation

### ISSUE THREAD

**Issue by ktsymbal** [open-craft-guild/open-source-guide#2]
I would love to contribute to the Ukrainian localisation of the Github open-source guide. 
Email: kate.glebova97---gmail-com

**Comment by webknjaz** [comment]
Action items:
* [x] invite to @open-source-guild/translators
* [x] invite to slack
  * [x] remove email from public access (to protect from spam-bots)
* [x] assign article/issue for translation

**Comment by webknjaz** [comment]
@kateGlebova introduce yourself to non-technical people in `#general` channel once you join LambdaBooks Slack.

**Comment by webknjaz** [comment]
@kateGlebova pick an issue, create a branch (name it `translation/##-article-name`) and start working on it.
