### ISSUE TITLE
Participation in the translation

### ISSUE THREAD

**Issue by numrut** [open-craft-guild/open-source-guide#3]
Hi, @webknjaz!

**Comment by webknjaz** [comment]
Action items:
* [x] invite to @open-source-guild/translators
* [x] invite to slack
  * [x] remove email from public access (to protect from spam-bots)
* [x] assign article/issue for translation

**Comment by webknjaz** [comment]
@numrut introduce yourself to non-technical people in `#general` channel once you join LambdaBooks Slack.

**Comment by numrut** [comment]
Hey @webknjaz, it seems I still haven't received an invitation.

**Comment by webknjaz** [comment]
@denysdovhan help

**Comment by webknjaz** [comment]
@numrut anyway you may pick any unassigned issue, create a branch (name it `translation/##-article-name`) and start working on it.
